baseURL = "/"
languageCode = "en-us"
title = "ito | Track infections, not people"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    # Site Params
    [languages.en.params]
    # Meta data
    description = "A privacy-first application for tracking infections using smart devices with bluetooth technology."
    author = "ito Organisation"

    # Navbar Menus
    [[languages.en.menu.main]]
    name    = "About"
    url     = "about"
    weight  = 2
    [[languages.en.menu.main]]
    name    = "Get Involved"
    url     = "onboarding"
    weight  = 3
    #[[languages.en.menu.main]]
    #name    = "Service"
    #url     = "service"
    #weight  = 4
    #[[languages.en.menu.main]]
    #name    = "Gallery"
    #url     = "gallery"
    #weight  = 5
    [[languages.en.menu.main]]
    name    = "Blog"
    url     = "blog"
    weight  = 6
    [[languages.en.menu.main]]
    name    = "Contact"
    url     = "contact"
    weight  = 7

    # Banner Section
    [languages.en.params.banner]
    enable  = true
    heading = "ito means"
    description = "Track infections, not people!"
    # button
    btn     = true
    btnText = "Get Involved"
    btnURL  = "onboarding"

    # flip text
    [[languages.en.params.banner.flipText]]
    title   = "Infection Termination Operation"
    [[languages.en.params.banner.flipText]]
    title   = "Integrated thermodynamic obscurity"
    [[languages.en.params.banner.flipText]]
    title   = "Infection Tracking Opportunity"
    [[languages.en.params.banner.flipText]]
    title   = "\"Thread\" in Japanese"

    # Homepage About Section
    [languages.en.params.about]
    enable  = true
    title   = "This is how it works"
    content = """\
        ito is a privacy-first contact tracing app to fight SARS-CoV-2 and other pathogens. 
        It uses Bluetooth to recognize which people are in your area and saves the information on your device.
        If someone from this history is reported as infected, your smartphone calculates your probability of infection and provides you with appropriate recommendations of action.
        If you have been tested positive yourself, you will receive a code from the health department that you can enter in the app.
        Your pseudonymized ID will then be uploaded together with the verification of the positive test.
        All users download the latest information at regular intervals to compare the data locally on their devices.
        When the device of a person who has been in contact with you recognizes this pseudonymized ID, they will be informed - without the actual identity being revealed.
            """
    image   = "images/about/woman-app.jpg"

    [languages.en.params.about2]
    enable  = true
    title   = "ito is made by people like you"
    content = """\
        ito emerged as part of a grassroots initiative in March 2020.
        Since then, we have been joined by many other interested individuals, professionals and companies.
        As part of the TCN coalition we are working together with other like minded teams around the world.
        """
    image   = "images/about/about.png"

    # Call to Action
    [languages.en.params.cta]
    enable  = true
    title   = "We work 100% transparently"
    content = "Because we mean it when we say we want to help the world stay safe, every part of our code is open-source."
    btnText = "Join Us"
    btnURL  = "/onboarding"

    # Portfolio Section On Homepage
    [languages.en.params.portfolio]
    enable  = false
    title   = "Latest Works"
    subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # social icons
    [[languages.en.params.socialIcon]]
    icon = "ion-social-github"
    url = "https://github.com/ito-org"

    [[languages.en.params.socialIcon]]
    icon = "ion-social-twitter"
    url = "https://twitter.com/BandemicApp"

    [[languages.en.params.socialIcon]]
    icon = "ion-social-youtube"
    url = "https://www.youtube.com/channel/UCYVYc99hjqv8cBSDvHwFGZQ/featured?view_as=subscriber"

    [[languages.en.params.socialIcon]]
    icon = "ion-social-instagram"
    url = "https://www.instagram.com/bandemic.app/"

  [languages.de]
    [languages.de.params]
    # Meta data
    description = "Eine Applikation zum Unterbrechen von Infektionsketten mithilfe von Bluetooth welche deine Privatsphäre schützt."
    author = "ito Organisation"

    # Navbar Menus
    [[languages.de.menu.main]]
    name    = "Über uns"
    url     = "de/about"
    weight  = 2
    [[languages.de.menu.main]]
    name    = "Mach mit!"
    url     = "de/onboarding"
    weight  = 3
    #[[languages.de.menu.main]]
    #name    = "Service"
    #url     = "de/service"
    #weight  = 3
    #[[languages.de.menu.main]]
    #name    = "Gallery"
    #url     = "de/gallery"
    #weight  = 4
    [[languages.de.menu.main]]
    name    = "Blog"
    url     = "de/blog"
    weight  = 5
    [[languages.de.menu.main]]
    name    = "Kontakt"
    url     = "de/contact"
    weight  = 6

    # Banner Section
    [languages.de.params.banner]
    enable  = true
    heading = "ito bedeutet"
    description = "Ortet Viren, nicht Menschen!"
    # button
    btn     = true
    btnText = "Mach mit!"
    btnURL  = "de/onboarding"
     # flip text
    [[languages.de.params.banner.flipText]]
    title   = "Infektions terminierungs Operation"
    [[languages.de.params.banner.flipText]]
    title   = "Integrated thermodynamic obscurity"
    [[languages.de.params.banner.flipText]]
    title   = "Infection Tracking Opportunity"
    [[languages.de.params.banner.flipText]]
    title   = "\"Faden\" auf Japanisch"

    # Homepage About Section
    [languages.de.params.about]
    enable  = true
    title   = "So funktioniert es"
    content = """\
        ito ist eine Anwendung zur Kontaktnachverfolgung um SARS-CoV-2 und anderen Krankheitserregern zu bekämpfen und dabei den Schutz der Privatsphäre zu waren.
        Sie verwendet Bluetooth, um zu erkennen, welche Personen sich in deiner Nähe aufhalten, und speichert die Informationen anonym auf deinem Gerät.
        Wenn sich jemand aus dieser Liste als infiziert meldet, berechnet dein Smartphone die Wahrscheinlichkeit einer Infektion und gibt dir entsprechende Handlungsempfehlungen.
        Wenn du selbst positiv getestet wirst, erhältst du von der Gesundheitsbehörde einen Code, mit dem in die App eine Meldung ausgelöst werden kann.
        Ihre Temporären Kontakt Nummern (TCN) werden dann auf den Server geladen, da die Nummern zufällig sind existiert kein Bezug zu dir.
        Alle Benutzer laden in regelmäßigen Abständen die neuesten Informationen herunter, um die Daten lokal auf ihren Geräten zu vergleichen.
        Wenn das Gerät einer Person, die mit dir Kontakt hatte, diese TCN erkennt, wird sie informiert - ohne dass deine tatsächliche Identität preisgegeben wird.
            """
    image   = "images/about/woman-app.jpg"

    [languages.de.params.about2]
    enable  = true
    title   = "ito wird von Menschen wie dir entwickelt"
    content = """\
        ito entstand im März 2020 als Teil einer Basisinitiative.
        Seitdem haben sich uns viele andere interessierte Einzelpersonen, Fachleute und Unternehmen angeschlossen.
        Als Teil der TCN-Koalition arbeiten wir mit anderen gleichgesinnten Teams auf der ganzen Welt zusammen.
              """
    image   = "images/about/about.png"

    # Call to Action
    [languages.de.params.cta]
    enable  = true
    title   = "Wir arbeiten 100% transparent"
    content = "Weil wir es ernst meinen, wenn wir sagen, dass wir jedem auf der Welt helfen wollen, gesund zu bleiben, ist jeder Teil unseres Codes quelloffen."
    btnText = "Hilf mit!"
    btnURL  = "/de/onboarding"

    # Portfolio Section On Homepage
    [languages.de.params.portfolio]
    enable  = false
    title   = "Latest Works"
    subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # social icons
    [[languages.de.params.socialIcon]]
    icon = "ion-social-github"
    url = "https://github.com/ito-org"

    [[languages.de.params.socialIcon]]
    icon = "ion-social-twitter"
    url = "https://twitter.com/BandemicApp"

    [[languages.de.params.socialIcon]]
    icon = "ion-social-youtube"
    url = "https://www.youtube.com/channel/UCYVYc99hjqv8cBSDvHwFGZQ/featured?view_as=subscriber"

    [[languages.de.params.socialIcon]]
    icon = "ion-social-instagram"
    url = "https://www.instagram.com/bandemic.app/"
